services:
  - type: web
    name: soar-siem-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        value: password
      - key: PYTHON_VERSION
        value: 3.11.0
